export const baseFormDefaults = {
  performanceType: '',
  artworkForm: '',
  artworkName: '',
  artworkLength: null,
  artworkWidth: null,
  creationTime: '',
  song1: '',
  song2: '',
  song1HasChinese: true,
  song1IsOriginal: false,
  song2HasChinese: true,
  song2IsOriginal: false,
  contact: '',
  phone: '',
  address: '',
  group: '',
  leader: '',
  tutor: '',
  notice: false
}
