export const baseFormDefaults = {
  performanceType: '',
  artworkName: '',
  performerCount: null,
  creationTime: '',
  song1: '',
  song2: '',
  minutes: 0,
  seconds: 0,
  song1HasChinese: true,
  song1IsOriginal: false,
  song2HasChinese: true,
  song2IsOriginal: false,
  contact: '',
  phone: '',
  address: '',
  group: '',
  leader: '',
  tutor: '',
  conductor: '',
  notice: false
}
